# Generated by Django 4.1.7 on 2023-04-03 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fullName', models.CharField(max_length=60)),
                ('phoneNum', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=150)),
            ],
        ),
    ]
