# Generated by Django 4.1.7 on 2023-02-26 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_vendor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
