# Generated by Django 4.1.7 on 2023-03-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipmentDate',
        ),
        migrations.AddField(
            model_name='order',
            name='shippmentDate',
            field=models.DateTimeField(null=True),
        ),
    ]
