# Generated by Django 4.1.7 on 2023-04-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='myComment',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='myRate',
            field=models.FloatField(null=True),
        ),
    ]
