# Generated by Django 4.1.7 on 2023-03-16 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_shipmentdate_order_shippmentdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shippmentDate',
            new_name='shipmentDate',
        ),
    ]
