# Generated by Django 4.1.7 on 2023-04-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderitem_commentagain'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='RRDate',
            field=models.DateTimeField(null=True),
        ),
    ]
