# Generated by Django 4.1.7 on 2023-04-03 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='vendor',
        ),
    ]
