# Generated by Django 4.1.7 on 2023-04-03 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_alter_vendor_user'),
        ('order', '0008_order_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='vendor',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor'),
        ),
    ]
