# Generated by Django 4.1.7 on 2023-02-26 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_vendor'),
        ('products', '0003_product_avgrating_alter_product_introduction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MyRate', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('PONumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.order')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
