# Generated by Django 4.1.7 on 2023-02-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
